image: cr.d.xiaomi.net/athena-public/athena_cross:latest

stages:
  - build
  - test

variables:
  GIT_SUBMODULE_STRATEGY: normal
  GIT_DEPTH: 1
  CROSS_SETUP_BASH_FILE: /mnt/sdcard/opt/ros2/foxy/local_setup.bash

before_script:
  - git config --global url."https://${GIT_CI_TOKEN}@partner-gitlab.mioffice.cn/".insteadOf "https://partner-gitlab.mioffice.cn/"
  - fusion-cli config --access-key ${FDS_AK} --secret-key ${FDS_SK}
  - locale-gen en_US.UTF-8 && export LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8
  - source ${CROSS_SETUP_BASH_FILE}

.limit: &limit
  tags:
    - group-runner

build:
  stage: build
  <<: *limit
  script:
    - make

test:
  stage: test
  <<: *limit
  script:
    - make test
